### PR TITLE
empyt

### PR DESCRIPTION
**Pull request by mlg87**

### CODE REVIEW

**Comment by mlg87** [comment]
SLACK_MESSAGE_ID:1597525668.085500

**Review by masonguild — APPROVED** [review]

**Review by masonguild — APPROVED** [review]

**Review by masonguild — APPROVED** [review]

**Review by masonguild — APPROVED** [review]

**Review by masonguild — APPROVED** [review]

**Review by masonguild — APPROVED** [review]

**Review by masonguild — CHANGES_REQUESTED** [review]
this needs to be better

**Review by masonguild — COMMENTED** [review]
whats up?

**Review by masonguild — APPROVED** [review]

**Review by masonguild — APPROVED** [review]
is there a body to this PR?

**Review by masonguild — APPROVED** [review]
holy shit i love this code so much

**Pull request merged**
