### PR TITLE
update to v4 of the action

### PR DESCRIPTION
**Pull request by mlg87**

### CODE REVIEW

**Comment by mlg87** [comment]
SLACK_MESSAGE_ID:1597557353.092700

**Review by masonguild — CHANGES_REQUESTED** [review]
what garbage code. you need to fix this

**Review by masonguild — CHANGES_REQUESTED** [review]
still shit

**Review by masonguild — COMMENTED** [review]
what am i looking at here?

**Review by masonguild — CHANGES_REQUESTED** [review]
actually, i figured it out and i want you to change it

**Review by masonguild — APPROVED** [review]
JK this is sick

**Pull request merged**
